[build]
  publish = "."

# Routes propres
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/cgu"
  to = "/cgu.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/conversations"
  to = "/conversations.html"
  status = 200

# Lien court : /u/UID -> profil public
[[redirects]]
  from = "/u/:uid"
  to   = "/profile-public.html?id=:uid"
  status = 200

# Catch-all SPA -> index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers sécurité + CSP (ENFORCÉE) — Firebase + AppCheck + Cloudinary + Crisp + Fonts
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' https: data: https://res.cloudinary.com https://*.crisp.chat;
      style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
      script-src 'self' https://www.gstatic.com https://client.crisp.chat https://*.crisp.chat 'unsafe-inline';
      font-src 'self' https://fonts.gstatic.com data:;
      connect-src 'self'
        https://*.firebaseio.com
        https://*.googleapis.com
        https://identitytoolkit.googleapis.com
        https://securetoken.googleapis.com
        https://www.googleapis.com
        https://www.gstatic.com
        https://firebasestorage.googleapis.com
        https://*.firebasestorage.app
        https://api.cloudinary.com
        https://client.crisp.chat https://*.crisp.chat wss://*.crisp.chat;
      frame-src https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/ https://client.crisp.chat https://*.crisp.chat;
      child-src https://www.google.com/recaptcha/ https://recaptcha.google.com/recaptcha/;
      frame-ancestors 'none';
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"