# netlify.toml — LoveNow (redirects + headers sécurité + CSP report-only)
[build]
  publish = "."

# Routes propres
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/cgu"
  to = "/cgu.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/conversations"
  to = "/conversations.html"
  status = 200

# Lien court pour profils publics : /u/UID -> profile-public.html?id=UID
[[redirects]]
  from = "/u/:uid"
  to   = "/profile-public.html?id=:uid"
  status = 200

# Catch-all SPA -> index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers sécurité (basics)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Content-Security-Policy en Report-Only (évite de casser la prod tout en testant)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' https:; font-src 'self' https: data:; report-to csp-endpoint;"
    Report-To = '{"group":"csp-endpoint","max_age":10886400,"endpoints":[{"url":"https://report-uri.com/"}]}'